[bot]
token             = "7672994737:AAE2OMcLyqFSFbv7l5H3YwVPLssMCIC8gPQ"
main_group_id     = -1003530310249
reports_group_id  = -1003753219003
utc_offset        = 0
date_format       = "%d.%m.%Y"
time_format       = "%H:%M"
remove_joins      = true
auto_ban_channels = true

[logs]
show_datetime          = true
datetime_format        = "%Y-%m-%d %H:%M:%S"
show_debug_logs        = true
time_in_utc            = false
use_colors_in_console  = false
renderer               = "json"
allow_third_party_logs = true
